### ISSUE TITLE
GitHub Workflow Configuration Issues

### ISSUE THREAD

**Issue by aygp-dr** [aygp-dr/isolated-pymcp#92]
## Description
The current GitHub workflow (.github/workflows/makefile.yml) is using a generic template with commands that don't exist in our Makefile. The workflow attempts to run `./configure`, `make check`, and `make distcheck` but our project uses a UV-based build system with different Makefile targets, causing all CI jobs to fail.

## Steps To Reproduce
1. Open .github/workflows/makefile.yml file
2. Review the build steps: `./configure`, `make`, `make check`, and `make distcheck`
3. Compare with our actual Makefile which uses targets like `dirs`, `tangle`, `lint`, `format`, etc.
4. Push any commit to the repository
5. Navigate to Actions tab and observe the workflow failure at the `./configure` step

## Expected Behavior
The GitHub workflow should execute our actual build process:
1. Set up Python 3.11 and UV package manager
2. Create directories with `make dirs`
3. Generate configs with `make tangle`
4. Install dependencies via UV
5. Run linting, formatting, and tests
6. Build Docker image and execute sandbox isolation tests

## Actual Behavior
The workflow fails immediately when trying to run the `./configure` command, which doesn't exist in our repository. No meaningful CI validation is performed, allowing potentially broken code to be merged.

## Environment
- OS: Linux pi 6.12.18-v8+ (aarch64)
- Python version: 3.11.2
- Claude version: 0.2.86 (Claude Code)
- Project version: v0.1.0
- Node.js version: v18.19.0

## Additional Context
Our project uses:
1. UV for Python package management instead of pip
2. Org-mode tangle for configuration generation requiring Emacs
3. A Docker/Podman container environment for isolation
4. Sandbox isolation tests that should be included in CI

**Current Workflow File:**
```yaml
name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: Install dependencies
      run: make
    - name: Run check
      run: make check
    - name: Run distcheck
      run: make distcheck
```

I recommend replacing it with a workflow that aligns with our actual build system as defined in the Makefile.
